service: serverlessSWAPI

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: "arn:aws:dynamodb:eu-west-1:549617601652:table/Persona"
        - Effect: Allow
          Action: "lambda:*"
          Resource: "*"
        - Effect: Allow
          Action: "apigateway:*"
          Resource: "*"

plugins:
  - serverless-auto-swagger
  - serverless-offline

functions:
  registrarPersona:
    handler: src/handlers/persona/registrarPersona.registrarPersona
    memorySize: 128 # mb
    timeout: 30 # seconds
    events:
      - http:
          method: POST
          path: "/api/persona"
  listarPersona:
    handler: src/handlers/persona/listarPersona.listarPersona
    memorySize: 128 # mb
    timeout: 30 # seconds
    events:
      - http:
          method: GET
          path: "/api/persona"
  traerPersona:
    handler: src/handlers/persona/traerPersona.traerPersona
    memorySize: 128 # mb
    timeout: 30 # seconds
    events:
      - http:
          method: GET
          path: "/api/persona/{id}"

resources:
  Resources:
    Persona:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Persona
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
