// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "serverlessSWAPI",
    "version": "1"
  },
  "paths": {
    "/api/persona": {
      "post": {
        "summary": "registrarPersona",
        "description": "",
        "operationId": "registrarPersona.post./api/persona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "listarPersona",
        "description": "",
        "operationId": "listarPersona.get./api/persona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/persona/{id}": {
      "get": {
        "summary": "traerPersona",
        "description": "",
        "operationId": "traerPersona.get./api/persona/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Persona": {
      "properties": {
        "id": {
          "title": "Persona.id",
          "type": "string"
        },
        "codigo_persona": {
          "title": "Persona.codigo_persona",
          "type": "number"
        },
        "anio_nacimiento": {
          "title": "Persona.anio_nacimiento",
          "type": "string"
        },
        "color_ojos": {
          "title": "Persona.color_ojos",
          "type": "string"
        },
        "genero": {
          "title": "Persona.genero",
          "type": "string"
        },
        "color_cabello": {
          "title": "Persona.color_cabello",
          "type": "string"
        },
        "altura": {
          "title": "Persona.altura",
          "type": "string"
        },
        "masa": {
          "title": "Persona.masa",
          "type": "string"
        },
        "nombre": {
          "title": "Persona.nombre",
          "type": "string"
        },
        "color_piel": {
          "title": "Persona.color_piel",
          "type": "string"
        }
      },
      "required": [
        "id",
        "codigo_persona",
        "anio_nacimiento",
        "color_ojos",
        "genero",
        "color_cabello",
        "altura",
        "masa",
        "nombre",
        "color_piel"
      ],
      "additionalProperties": false,
      "title": "Persona",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};